name: Scheduled Crawl

on:
  schedule:
    - cron: "*/6 * * * *" # Runs every 12 minutes
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate TLD folders (idempotent)
        run: |
          python scripts/init_folders.py
      - name: Run crawler (respects robots.txt)
        timeout-minutes: 5 # Allow crawl to run for up to 10 minutes
        run: |
          python scripts/crawl.py
      - name: Commit and push changes
        if: always() # Attempt to commit even if previous steps fail or are cancelled
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add domains/ data/
          git commit -m 'chore: update crawl results [skip ci]' || echo 'No changes to commit'
          git push
